#pragma once

x_fn_1_t x_string_p;
x_fn_1_t x_string_length;
x_fn_1_t x_string_empty_p;
x_fn_1_t x_string_blank_p;
x_fn_3_t x_string_substring;
x_fn_2_t x_string_append;
x_fn_1_t x_string_concat;
x_fn_2_t x_string_compare_lexical;
x_fn_1_t x_string_to_symbol;
x_fn_1_t x_string_chars;
x_fn_1_t x_string_lines;
x_fn_2_t x_string_split;
x_fn_2_t x_string_join;
x_fn_3_t x_string_replace;
x_fn_2_t x_string_starts_with_p;
x_fn_2_t x_string_ends_with_p;
x_fn_1_t x_string_to_upper_case;
x_fn_1_t x_string_to_lower_case;
x_fn_2_t x_string_get_code_point;
x_fn_2_t x_string_contains_p;
x_fn_2_t x_string_find_index;
x_fn_1_t x_string_trim_left;
x_fn_1_t x_string_trim_right;
x_fn_1_t x_string_trim_start;
x_fn_1_t x_string_trim_end;
x_fn_1_t x_string_trim;
