#pragma once

x_fn_0_t x_make_list;
x_fn_1_t x_any_list_p;
x_fn_1_t x_list_copy;
x_fn_1_t x_list_length;
x_fn_1_t x_list_empty_p;
x_fn_1_t x_list_pop_mut;
x_fn_2_t x_list_push_mut;
x_fn_2_t x_list_push;
x_fn_1_t x_list_shift_mut;
x_fn_2_t x_list_unshift_mut;
x_fn_2_t x_list_get;
x_fn_3_t x_list_put_mut;
x_fn_3_t x_list_put;
x_fn_1_t x_car;
x_fn_1_t x_cdr;
x_fn_2_t x_cons;
x_fn_1_t x_list_head;
x_fn_1_t x_list_tail;
x_fn_1_t x_list_init;
x_fn_1_t x_list_last;
x_fn_1_t x_list_reverse_mut;
x_fn_1_t x_list_reverse;
x_fn_1_t x_list_to_set;
