#pragma once

#include "deps.h"
#include "types.h"
#include "value.h"

#include "x_int.h"
#include "x_float.h"
#include "x_little.h"
#include "x_bool.h"
#include "x_void.h"
#include "x_null.h"
#include "x_object.h"
#include "x_value.h"
#include "x_console.h"
#include "x_address.h"
#include "x_apply.h"
#include "x_random.h"
#include "x_curry.h"
#include "x_function.h"
