#!/usr/bin/env bash

update-submodules () {
    git submodule init
    git submodule update
    git submodule update --remote
}

deps () {
    update-submodules
    for SUBMODULE in $(find deps/ -maxdepth 1 -mindepth 1)
    do
        pushd $SUBMODULE && sbt publishLocal && popd
    done
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
