#pragma once

#include "deps.h"
#include "types.h"
#include "instr.h"
#include "primitive.h"
#include "function.h"
#include "definition.h"
#include "program.h"
#include "xvm.h"
#include "frame.h"
#include "define.h"
#include "call.h"
#include "apply.h"
#include "closure.h"
#include "xvm_asm.h"
#include "xvm_exe.h"
